spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root
    database: tinkoff_java
    driverClassname: org.postgresql.Driver